const fs = require('fs');
const catalog = JSON.parse(fs.readFileSync('components.json', 'utf8'));
const existing = new Set(catalog.map(c => c.slug));

const toAdd = [
  // Phase 3e — Overlay/Popover
  { slug: 'tooltip-variants', title: 'Tooltip Variants', description: 'A reference panel of tooltip placements and variants. Hovering each target reveals its tooltip at top, right, bottom, or left position. Also demonstrates icon-only tooltips and rich tooltips with a title, body text, and CTA link.', category: 'Feedback', tags: ['tooltip', 'hover', 'placement', 'variants', 'label'], style: 'functional' },
  { slug: 'popover-with-actions', title: 'Popover with Actions', description: 'A button-triggered popover panel with a contextual action list: Share, Copy link, Rename, and Delete (danger-styled with a separator). Clicking outside or pressing Escape closes the popover. Keyboard shortcuts shown per action.', category: 'Feedback', tags: ['popover', 'actions', 'menu', 'outside-click', 'overlay'], style: 'functional' },
  { slug: 'hover-card-preview', title: 'Hover Card Preview', description: 'Hover any member row to reveal a rich user profile card with avatar, name, role, bio, and 3 key stats. The card appears beneath the hovered row with a smooth transition.', category: 'Feedback', tags: ['hover-card', 'preview', 'user', 'popover', 'card'], style: 'functional' },
  { slug: 'dropdown-menu-nested', title: 'Dropdown Menu Nested', description: 'A single-level dropdown where one item ("Move to") opens a second-level submenu on hover. The submenu appears to the right. Includes Copy, Rename, Archive, and Delete items with keyboard shortcuts.', category: 'Navigation', tags: ['dropdown', 'nested', 'submenu', 'menu', 'chevron'], style: 'functional' },
  { slug: 'color-picker-popover', title: 'Color Picker Popover', description: 'A swatch-grid color picker in a popover. 24 preset swatches plus a hex code input field. Selected color updates the trigger preview. Enter in the hex field or clicking a swatch selects and closes.', category: 'Inputs', tags: ['color-picker', 'swatch', 'popover', 'hex', 'palette'], style: 'functional' },
  { slug: 'rich-tooltip', title: 'Rich Tooltip', description: 'Rich tooltips that include a title, body description, and a "Learn more" CTA link. Hover any labeled feature element to reveal the dark tooltip with full content. Four feature items are shown.', category: 'Feedback', tags: ['tooltip', 'rich', 'cta', 'description', 'hover', 'help'], style: 'functional' },

  // Phase 3f — Cards/Lists
  { slug: 'profile-card', title: 'Profile Card', description: 'User profile card with avatar, display name, username, role badge, bio, and a 3-stat row (Followers, Following, Projects). Follow button toggles to Unfollow with a checkmark. Message secondary CTA.', category: 'Cards', tags: ['profile', 'user', 'avatar', 'stats', 'follow', 'card'], style: 'functional' },
  { slug: 'project-card', title: 'Project Card', description: 'Project card showing name, description, tag chips, a member avatar stack with overflow count, and a status badge. Three cards in Active, In Review, and Planning states.', category: 'Cards', tags: ['project', 'card', 'tags', 'status', 'members', 'avatars'], style: 'functional' },
  { slug: 'stat-change-card', title: 'Stat Change Card', description: '2×2 grid of KPI cards each with a large metric value, percentage delta with TrendingUp/Down icon, period label, and an inline SVG sparkline. Covers revenue, active users, conversion, and P95 latency.', category: 'Cards', tags: ['stat', 'sparkline', 'delta', 'metric', 'card', 'kpi'], style: 'functional' },
  { slug: 'file-upload-card', title: 'File Upload Card', description: 'Drag-and-drop file upload zone that accepts any file. Dropped files appear in a list with file name, size, type icon, and a simulated upload progress bar over 2 seconds. Completed files show a green check.', category: 'Cards', tags: ['file-upload', 'drag-drop', 'progress', 'list', 'upload', 'card'], style: 'functional' },
  { slug: 'checklist-card', title: 'Checklist Card', description: 'A titled card with a 6-item release checklist. Items toggle individually with Circle/CheckCircle2. A progress bar fills as tasks complete. Reaching 100% shows a green "Ready to ship" banner.', category: 'Cards', tags: ['checklist', 'task', 'card', 'todo', 'progress', 'compact'], style: 'functional' },
  { slug: 'activity-feed-card', title: 'Activity Feed Card', description: 'Activity feed showing a stream of user events: commits, reviews, comments, deploys, merges, and doc edits. Each entry has a type-colored icon, user name, action text, target, and relative timestamp. Loads more events on demand.', category: 'Cards', tags: ['activity', 'feed', 'event', 'card', 'timeline', 'user'], style: 'functional' },

  // Phase 3g — Misc depth
  { slug: 'color-mode-toggle', title: 'Color Mode Toggle', description: 'A segmented 3-way toggle for Light, System, and Dark mode with a sliding pill indicator. Selecting a mode previews a mini UI swatch with the corresponding color palette.', category: 'Inputs', tags: ['dark-mode', 'light-mode', 'system', 'toggle', 'theme', '3-way'], style: 'functional' },
  { slug: 'keyboard-shortcut-legend', title: 'Keyboard Shortcut Legend', description: 'Two-column shortcut reference table organized into Navigation, Editing, and View sections. Each row shows an action name and styled keyboard key chips with a box-shadow bottom border.', category: 'Data Display', tags: ['keyboard', 'shortcuts', 'legend', 'reference', 'keybinding', 'table'], style: 'functional' },
  { slug: 'scroll-to-top-button', title: 'Scroll To Top Button', description: 'A floating "scroll to top" FAB that fades in after the user scrolls 80px inside the bounded container. Button slides up as it appears. Clicking scrolls the container back to the top smoothly.', category: 'Navigation', tags: ['scroll', 'back-to-top', 'fab', 'floating', 'button'], style: 'functional' },
  { slug: 'copy-to-clipboard-button', title: 'Copy To Clipboard Button', description: 'Four copy-to-clipboard variants in one panel: icon-only, icon+label, terminal snippet row, and API key row. Each independently shows a 1.5-second success checkmark and Copied label on click.', category: 'Buttons', tags: ['copy', 'clipboard', 'button', 'confirmation', 'check', 'feedback'], style: 'functional' },
  { slug: 'avatar-group', title: 'Avatar Group', description: 'Stacked avatar row with three density sizes (sm, md, lg). Shows up to 5 member initials with an overflow "+N" counter. Hovering any avatar reveals the member name in a tooltip.', category: 'Data Display', tags: ['avatar', 'group', 'stack', 'overflow', 'members', 'faces'], style: 'functional' },
  { slug: 'rating-stars', title: 'Rating Stars', description: 'Interactive 5-star rating where stars fill yellow on hover and lock on click. A read-only variant shows a locked score with partial star support via CSS clip-path. Both interactive and two read-only examples are shown.', category: 'Inputs', tags: ['rating', 'stars', 'interactive', 'hover', 'review'], style: 'functional' },
  { slug: 'drag-drop-list', title: 'Drag Drop List', description: 'Reorderable list using the native drag API without any third-party library. Grabbing an item dims it at 40% opacity while a highlight border appears on the drop target. Dropping reorders the list instantly.', category: 'Inputs', tags: ['drag-drop', 'reorder', 'list', 'pointer', 'sortable'], style: 'functional' },
  { slug: 'rich-text-toolbar', title: 'Rich Text Toolbar', description: 'Formatting toolbar with Bold, Italic, Underline, Strikethrough, Alignment, Bullet list, Numbered list, Highlight, and Link buttons. A font-size selector is included. All toggles apply preview styles to a sample text block below the toolbar.', category: 'Inputs', tags: ['rich-text', 'editor', 'toolbar', 'bold', 'italic', 'formatting'], style: 'functional' },
  { slug: 'data-export-button', title: 'Data Export Button', description: 'A compound split-style export button. Primary half shows the selected format and triggers export. Chevron half opens a dropdown to pick CSV, JSON, or Excel. Export shows a loading spinner then a success state.', category: 'Buttons', tags: ['export', 'csv', 'json', 'download', 'format-selector', 'data'], style: 'functional' },

  // Phase 3h — Extra fills
  { slug: 'inline-edit-field', title: 'Inline Edit Field', description: 'Click any labeled text field to edit it in-place. The label becomes an input on click. Enter or blur saves, Escape reverts. A hover pencil icon hints at editability. Four fields: Name, Title, Email, Team.', category: 'Inputs', tags: ['inline-edit', 'in-place', 'click-to-edit', 'editable', 'field'], style: 'functional' },
  { slug: 'skeleton-loader', title: 'Skeleton Loader', description: 'Content loading skeletons with a CSS shimmer animation. Shows a card skeleton (avatar, text lines, buttons) and a list item skeleton. After 1.8 seconds, reveals the real content. A Reset button re-triggers the loading state.', category: 'Loading', tags: ['skeleton', 'placeholder', 'loading', 'shimmer', 'content'], style: 'functional' },
  { slug: 'filter-chips', title: 'Filter Chips', description: 'Toggleable filter chip row where multiple chips can be active at once. An "All" chip clears all selections. Items below the chips dynamically filter to those matching at least one active chip. Active chips show an X.', category: 'Navigation', tags: ['filter', 'chips', 'tags', 'toggle', 'facets', 'multi-select'], style: 'functional' },
  { slug: 'expandable-text', title: 'Expandable Text', description: 'Long text blocks clamped to 3 lines with a "Read more / Read less" toggle button. Three independent blocks with design systems, performance, and accessibility content — each with isolated expand state.', category: 'Data Display', tags: ['read-more', 'truncate', 'expand', 'collapse', 'text', 'clamp'], style: 'functional' },
  { slug: 'floating-label-input', title: 'Floating Label Input', description: 'Animated floating label inputs where the label transitions from placeholder position to a small label above the input on focus or value entry. Full Name, Email, Password (show/hide), and Company fields.', category: 'Inputs', tags: ['floating-label', 'input', 'animated', 'label', 'focus'], style: 'functional' },
  { slug: 'confirmation-dialog', title: 'Confirmation Dialog', description: 'Modal confirmation dialog for destructive actions. Trigger opens a dialog with AlertTriangle icon, warning message, and Cancel/Delete buttons. Confirming shows a 1.4s loading state then a green success state.', category: 'Feedback', tags: ['dialog', 'confirm', 'cancel', 'destructive', 'modal', 'alert'], style: 'functional' },
  { slug: 'page-header', title: 'Page Header', description: 'Three page header layout variants in one panel: a project header with breadcrumb, title, and action buttons; a settings header with tabs; and a list header with a search input and invite button.', category: 'Layout', tags: ['page-header', 'title', 'subtitle', 'breadcrumb', 'actions', 'header'], style: 'functional' },
  { slug: 'split-button', title: 'Split Button', description: 'Compound button with a primary action on the left and a chevron that opens a dropdown of alternate actions on the right. Three variants: Save, Publish, and Deploy. All show loading and success states.', category: 'Buttons', tags: ['split-button', 'dropdown', 'alternate-action', 'compound', 'button'], style: 'functional' },
  { slug: 'time-picker', title: 'Time Picker', description: 'Time picker with ChevronUp/Down spinners for hour and minute fields and an AM/PM toggle. Hour wraps 12→1. Minutes snap to 5-minute intervals. A 24-hour format display updates in real time below the picker.', category: 'Inputs', tags: ['time', 'picker', 'hour', 'minute', 'am-pm', 'input', 'clock'], style: 'functional' },
  { slug: 'badge-overflow', title: 'Badge Overflow', description: 'Tag badge rows where excess items beyond a max threshold collapse into a "+N more" pill. Clicking the overflow badge expands to show all tags. A "Show less" link collapses back. Three rows with different tag sets.', category: 'Data Display', tags: ['badge', 'overflow', 'tags', 'list', 'compact', 'more'], style: 'functional' },
  { slug: 'media-card', title: 'Media Card', description: 'Video/media preview card with colored gradient thumbnail, play button overlay on hover, duration badge, title, and metadata row (author, views, date). Three cards for different content types stacked vertically.', category: 'Cards', tags: ['media', 'card', 'thumbnail', 'image', 'play', 'video'], style: 'functional' },
  { slug: 'accordion', title: 'Accordion', description: 'FAQ accordion with single-open behavior. Clicking a header opens it and closes the previously open one. Animated ChevronDown rotates 180° on open. Five FAQ items about billing, pricing, data storage, and cancellation.', category: 'Layout', tags: ['accordion', 'collapsible', 'faq', 'expand', 'collapse', 'disclosure'], style: 'functional' },
  { slug: 'sortable-table-columns', title: 'Sortable Table Columns', description: 'Data table where clicking a column header cycles through ascending → descending → unsorted. Arrow icon indicates sort direction. Rows reorder live. One column sorts at a time.', category: 'Tables', tags: ['sort', 'table', 'columns', 'ascending', 'descending', 'arrow'], style: 'functional' },
];

let added = 0;
for (const item of toAdd) {
  if (existing.has(item.slug)) { console.log('skip:', item.slug); continue; }
  const codePath = 'components/' + item.slug + '.tsx';
  let code = '';
  try { code = fs.readFileSync(codePath, 'utf8'); } catch(e) { console.warn('no file for', item.slug); continue; }
  catalog.push({
    ...item,
    sourceUrl: 'https://raw.githubusercontent.com/gkstrmtm/exhibit/main/components/' + item.slug + '.tsx',
    code,
  });
  added++;
}

fs.writeFileSync('components.json', JSON.stringify(catalog, null, 2));
console.log('Added', added, 'components. Total:', catalog.length);
